import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

//internal import
import { ChatAppProvider } from "@/Context/ChatAppContext";
import Navbar from "./Navbar/Navbar";
export const metadata = {
  title: "Decentralized Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ChatAppProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar className="p-0" />
          {children}
        </body>
      </html>
    </ChatAppProvider>
  );
}
